config/routes.rb
Openresponsive::Application.routes.draw do

match '/auth/:provider/callback' => "developers#create"

match '/signout' => 'developers#signout'

  resources :developers

  root to: 'static_site#home'

  resources :casestudies

  resources :partners

  resources :products

  get "static_site/home"

  get "static_site/about"

  get "static_site/contact"

  resources :teams

  resources :services

  resources :portfolios

  resources :clients

  resources :careers

  resources :blogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/career.rb
class Career < ActiveRecord::Base
  attr_accessible :description, :how_to_apply, :job_name
end

app/models/casestudy.rb
class Casestudy < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :client_project, :country, :email, :name, :project_description, :project_dude_date, :project_start_date, :state, :zip
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :partner_name, :website
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :description, :project_name, :project_website
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :domain, :features, :name
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :description, :desgination, :email, :facebook_url, :github_id, :name, :personal_website
end

app/controllers/portfolios_controller.rb
class PortfoliosController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/portfolios/_form.html.erb
<%= simple_form_for(@portfolio) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :project_name %>
    <%= f.input :description %>
    <%= f.input :project_website %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Editing portfolio</h1>

<%= render 'form' %>

<%= link_to 'Show', @portfolio %> |
<%= link_to 'Back', portfolios_path %>

app/views/portfolios/index.html.erb
<h1>Listing portfolios</h1>

<table>
  <tr>
    <th>Project name</th>
    <th>Description</th>
    <th>Project website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.project_name %></td>
    <td><%= portfolio.description %></td>
    <td><%= portfolio.project_website %></td>
    <td><%= link_to 'Show', portfolio %></td>
    <td><%= link_to 'Edit', edit_portfolio_path(portfolio) %></td>
    <td><%= link_to 'Destroy', portfolio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Portfolio', new_portfolio_path %>

app/views/portfolios/new.html.erb
<h1>New portfolio</h1>

<%= render 'form' %>

<%= link_to 'Back', portfolios_path %>

app/views/portfolios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Project name:</b>
  <%= @portfolio.project_name %>
</p>

<p>
  <b>Description:</b>
  <%= @portfolio.description %>
</p>

<p>
  <b>Project website:</b>
  <%= @portfolio.project_website %>
</p>


<%= link_to 'Edit', edit_portfolio_path(@portfolio) %> |
<%= link_to 'Back', portfolios_path %>