config/routes.rb
Openresponsive::Application.routes.draw do

match '/auth/:provider/callback' => "developers#create"

match '/signout' => 'developers#signout'

  resources :developers

  root to: 'static_site#home'

  resources :casestudies

  resources :partners

  resources :products

  get "static_site/home"

  get "static_site/about"

  get "static_site/contact"

  resources :teams

  resources :services

  resources :portfolios

  resources :clients

  resources :careers

  resources :blogs

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :content, :name
end

app/models/career.rb
class Career < ActiveRecord::Base
  attr_accessible :description, :how_to_apply, :job_name
end

app/models/casestudy.rb
class Casestudy < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/client.rb
class Client < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :client_project, :country, :email, :name, :project_description, :project_dude_date, :project_start_date, :state, :zip
end

app/models/developer.rb
class Developer < ActiveRecord::Base
  attr_accessible :provider, :uid, :user_id
end

app/models/partner.rb
class Partner < ActiveRecord::Base
  attr_accessible :partner_name, :website
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  attr_accessible :description, :project_name, :project_website
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :description, :domain, :features, :name
end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :description, :name
end

app/models/team.rb
class Team < ActiveRecord::Base
  attr_accessible :description, :desgination, :email, :facebook_url, :github_id, :name, :personal_website
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/casestudies_helper.rb
module CasestudiesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/partners_helper.rb
module PartnersHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for(@client) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :address1 %>
    <%= f.input :address2 %>
    <%= f.input :city %>
    <%= f.input :state %>
    <%= f.input :country %>
    <%= f.input :zip %>
    <%= f.input :client_project %>
    <%= f.input :project_description %>
    <%= f.input :project_start_date %>
    <%= f.input :project_dude_date %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Address1</th>
    <th>Address2</th>
    <th>City</th>
    <th>State</th>
    <th>Country</th>
    <th>Zip</th>
    <th>Client project</th>
    <th>Project description</th>
    <th>Project start date</th>
    <th>Project dude date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.email %></td>
    <td><%= client.address1 %></td>
    <td><%= client.address2 %></td>
    <td><%= client.city %></td>
    <td><%= client.state %></td>
    <td><%= client.country %></td>
    <td><%= client.zip %></td>
    <td><%= client.client_project %></td>
    <td><%= client.project_description %></td>
    <td><%= client.project_start_date %></td>
    <td><%= client.project_dude_date %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @client.name %>
</p>

<p>
  <b>Email:</b>
  <%= @client.email %>
</p>

<p>
  <b>Address1:</b>
  <%= @client.address1 %>
</p>

<p>
  <b>Address2:</b>
  <%= @client.address2 %>
</p>

<p>
  <b>City:</b>
  <%= @client.city %>
</p>

<p>
  <b>State:</b>
  <%= @client.state %>
</p>

<p>
  <b>Country:</b>
  <%= @client.country %>
</p>

<p>
  <b>Zip:</b>
  <%= @client.zip %>
</p>

<p>
  <b>Client project:</b>
  <%= @client.client_project %>
</p>

<p>
  <b>Project description:</b>
  <%= @client.project_description %>
</p>

<p>
  <b>Project start date:</b>
  <%= @client.project_start_date %>
</p>

<p>
  <b>Project dude date:</b>
  <%= @client.project_dude_date %>
</p>


<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>